### ISSUE TITLE
Hard-coded params

### ISSUE THREAD

**Issue by abhi2610** [quantombone/exemplarsvm#11]
Just to maintain a list of hard-coded params such that we both are on the same page.

MAXDIM is hardcoded in https://github.com/quantombone/exemplarsvm/blob/master/initialize_goalsize_model.m
I prefer a different size for different experiments. That can be moved to init_params.

**Comment by quantombone** [comment]
Sounds good, in this case the name of the variable is misleading, but you're right that there is no reason why this shouldn't be inside the params -- I'll update it.

**Comment by quantombone** [comment]
this is fixed now, and check out demo_framing.m and the associated pdf generated in the pdfs/ folder to see examples of how to use this stuff.
