### ISSUE TITLE
init_params missing.

### ISSUE THREAD

**Issue by abhi2610** [quantombone/exemplarsvm#12]
init_params is missing in function signature while calling init_function in exemplar_initialize (line 90).

P.S: Is this right place to report and track bugs?

**Comment by quantombone** [comment]
What I actually did was something like:

``````
%Initialize framing function
init_params.sbin = 8;
init_params.hg_size = [8 8];
init_params.goal_ncells = 100;
init_function = @(a,b)initialize_fixedframe_model(a,b,init_params);```

This means that the init_function takes only two arguments (because it already has knowledge of init_params.  I just didn't want to pass around init_params, if those params are only used as the third argument to initialize_fixedframe_model.m
``````

**Comment by quantombone** [comment]
This example is from https://github.com/quantombone/exemplarsvm/blob/master/scripts/voc_template_exemplar_seg.m

**Comment by quantombone** [comment]
I made it so now you only pass init_params, and init_params has a field init_params.init_function which is the function handle to use.
