### ISSUE TITLE
where is the voc_demo_apply.m?

### ISSUE THREAD

**Issue by Ian09** [quantombone/exemplarsvm#39]
Hi, I have download the code and wanna test the result on VOC2007 . after that I want to use Exemplar SVM in my research work. BUT I do not find the demo code as in the read me file says: For evaluating the PASCAL VOC 2007 pre-trained exemplars, see the notes ...and the main evaluation function in [exemplarsvm/demos/voc_demo_apply.m] .

would you please give me the apply demo code or just tell me how to use the code to detect an object(such as bus) in a image?

Thanks very much!

**Comment by quantombone** [comment]
oops sorry, going to get the demo up

**Comment by Ian09** [comment]
looking forward to seeing your great demo! Thanks very much!

**Comment by quantombone** [comment]
you can take a sneak peek into the v1 branch, but I have to do more testing until the final v1.0 release

**Comment by quantombone** [comment]
Check out the updated README in the main folder, and models are in http://people.csail.mit.edu/tomasz/exemplarsvm/models/
