### ISSUE TITLE
How long should the computer run the voc_demo_esvm to train a classifier? 

### ISSUE THREAD

**Issue by Ian09** [quantombone/exemplarsvm#42]
hi, I download the code, and wanna train the voc2007 classifiers for myself, such as bus, bicycle etc.
my computer is intel i5(2 cores, 4 threads), and memory is 6GB, OS is linux federal. 
I have run the voc_demo_esvm for almost 10 hours, but it seems that it is still training.
So, How long do you think my computer should run for just a class, such as bus in VOC 2007 dataset?

**Comment by quantombone** [comment]
on my quad-core iMac with an SSD and 16GB RAM the training process takes about 10 hours for one of the small VOC2007 categories such as bus.  I would take a look into the directories which are created during training, first check the number of exemplar that were successfully trained (look inside models folder), then once training finished see how many trainval/test images have been processed (look into the applied folder).

The implementation doesn't use multiple cores, you should concurrently run the script N times where you have N cores on a machine.  This was designed to run across a clusters of {dozens, hundreds, thousands, or millions} of nodes.

Please stay tuned for a cleaned up API and models files! (or take a sneak peak at the v1 branch on github)
