### ISSUE TITLE
Issue with esvm_demo_apply_exemplars

### ISSUE THREAD

**Issue by cmethani** [quantombone/exemplarsvm#45]
Hi,

When trying to run your code, I get an error saying 

"Undefined function or variable 'features' "

Error in esvm_detect>esvm_detectdriverBLOCK (line 255)
templates = zeros(S(1),S(2),features,length(models));

"features" looks like an integer value which has not been initialized. Can you tell me what value it should take?

I am running this code on Windows XP.

**Comment by quantombone** [comment]
Hey, you must have checkout out the code in the middle of an edit.  That line has since then been changed, let me know if you are still having issues, or if the issue went away.

--Tomasz

**Comment by cmethani** [comment]
Hi, I am able to work around that issue. It seems that Matlab was not able
to locate the function "features" in the features directory.

On Thu, Jan 19, 2012 at 4:25 AM, Tomasz Malisiewicz <
reply@reply.github.com

**Comment by quantombone** [comment]
Ok cool, I replaced features.m with esvm_features.m to avoid conflict with Pedro's features.m

If you do a git pull, you'll get the most recent changes which are working as advertised.
--Tomasz
