### ISSUE TITLE
semantics of fg/bg sets

### ISSUE THREAD

**Issue by quantombone** [quantombone/exemplarsvm#7]
During mining and testing, we should make sure that fg is used for "foreground" sets and bg for "background" sets.  It might be confusing for a new user if they see bg used instead of fg.

**Comment by quantombone** [comment]
I think this is fixed.. but I should make sure before closing

**Comment by abhi2610** [comment]
I will use that by tonight or tomorrow to confirm the same as sanity check.

**Comment by abhi2610** [comment]
Makes sense to me, and I am comfortable using it.
More intuitive than before.
Issue closed from my end.

**Comment by quantombone** [comment]
I also changed get_pascal_bg to get_pascal_set, because this function is used to get sets for whatever use you want
