### ISSUE TITLE
32-dim hog descriptor?

### ISSUE THREAD

**Issue by quantombone** [quantombone/exemplarsvm#9]
if we use the most recent hog descriptor code, it will be 32 numbers because there is the 'outside' image bin present.
should we go with it?

**Comment by abhi2610** [comment]
I believe that it will require us to then clip that region later while detection/matching? Tell me if I am mistaken!

**Comment by quantombone** [comment]
In the current codebase, we can already produce detections that fall outside of the image.  I already take really good care of initializing the regions and creating a mask over which I perform the learning (the mask indicates which cells are inside the image and roughly inside the specified bb box)

**Comment by quantombone** [comment]
This is not really an issue with the current code, enabling new features (whether they are HOG++, mean RGB values per cell, texton-histogram per cell) is already present.  32-feature dim is more of a 'feature request', so I'm closing this for now.
